import { sql } from "@vercel/postgres";
import Link from "next/link";
import { notFound } from "next/navigation";
import ShareButton from "@/components/ShareButton";
import DeleteButton from "@/components/DeleteButton";

export const dynamic = 'force-dynamic';

interface Post {
    id: number;
    title: string;
    content: string;
    created_at: Date;
}

export default async function Post(props: { params: Promise<{ id: string }> }) {
    const params = await props.params;
    const { id } = params;
    let post: Post | undefined;
    try {
        const { rows } = await sql<Post>`SELECT * FROM posts WHERE id = ${id}`;
        post = rows[0];
    } catch (error) {
        console.error("Database Error:", error);
    }

    if (!post) {
        notFound();
    }

    return (
        <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-12 px-4 sm:px-6 lg:px-8 font-sans">
            <article className="max-w-3xl mx-auto bg-white dark:bg-gray-800 rounded-2xl shadow-2xl overflow-hidden ring-1 ring-gray-900/5">

                {/* Header */}
                <div className="relative bg-gradient-to-r from-blue-600 to-purple-600 p-8 sm:p-12 text-white">
                    <div className="flex justify-between items-start mb-8">
                        <Link href="/" className="inline-flex items-center text-blue-100 hover:text-white transition-colors">
                            <svg className="w-5 h-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                            </svg>
                            Back to Insights
                        </Link>
                        {/* Share Button */}
                        <div className="text-gray-900">
                            <ShareButton />
                        </div>
                    </div>

                    <h1 className="text-3xl sm:text-5xl font-extrabold mb-4 leading-tight">
                        {post.title}
                    </h1>
                    <div className="flex items-center space-x-4 text-blue-100 text-sm font-medium">
                        <time dateTime={new Date(post.created_at).toISOString()}>{new Intl.DateTimeFormat('ko-KR', { timeZone: 'Asia/Seoul', year: 'numeric', month: 'long', day: 'numeric', weekday: 'long' }).format(new Date(post.created_at))}</time>
                        <span>•</span>
                        <span>AI Analysis</span>
                    </div>
                </div>

                {/* Content */}
                <div className="p-8 sm:p-12">
                    <div
                        className="prose prose-lg dark:prose-invert max-w-none 
              prose-headings:font-bold prose-headings:text-gray-900 dark:prose-headings:text-white 
              prose-p:text-gray-700 dark:prose-p:text-gray-300 prose-p:leading-relaxed 
              prose-a:text-blue-600 dark:prose-a:text-blue-400 prose-a:no-underline hover:prose-a:underline
              prose-li:text-gray-700 dark:prose-li:text-gray-300
              prose-strong:text-gray-900 dark:prose-strong:text-white"
                        dangerouslySetInnerHTML={{ __html: post.content }}
                    />
                </div>

                {/* Footer */}
                <div className="bg-gray-50 dark:bg-gray-700/50 px-8 py-6 border-t border-gray-100 dark:border-gray-700 flex justify-between items-center">
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                        Generated by Gemini 2.5 Flash Lite & Brave Search
                    </p>
                    {/* Delete Button (Admin Only) */}
                    <div>
                        <DeleteButton id={post.id} />
                    </div>
                </div>
            </article>
        </div>
    );
}
